# Generated by Django 5.1.2 on 2025-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('year_of_model', models.IntegerField()),
                ('year_of_sign', models.IntegerField()),
                ('daily', models.FloatField()),
                ('weekly', models.FloatField()),
                ('monthly', models.FloatField()),
                ('yearly', models.FloatField()),
                ('main_pic', models.ImageField(upload_to='main pics/')),
                ('second_pic', models.ImageField(blank=True, upload_to='other pics/')),
                ('third_pic', models.ImageField(blank=True, upload_to='other pics/')),
                ('fourth_pic', models.ImageField(blank=True, upload_to='other pics/')),
                ('fifth_pic', models.ImageField(blank=True, upload_to='other pics/')),
            ],
        ),
    ]
