# Generated by Django 5.1.2 on 2025-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fifth_pic',
            field=models.ImageField(blank=True, null=True, upload_to='other_pics/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fourth_pic',
            field=models.ImageField(blank=True, null=True, upload_to='other_pics/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_pic',
            field=models.ImageField(upload_to='main_pics/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='second_pic',
            field=models.ImageField(blank=True, null=True, upload_to='other_pics/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='third_pic',
            field=models.ImageField(blank=True, null=True, upload_to='other_pics/'),
        ),
    ]
