# Generated by Django 5.1.2 on 2025-09-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_fifth_pic_alter_car_fourth_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
